changelog:
  exclude:
    authors:
      - renovate
      - dependabot
  categories:
    - title: "Breaking changes"
      labels: ["PR type: breaking 💥"]
    - title: "Features"
      labels: ["PR type: feature ⭐️"]
    - title: "Bug Fixes"
      labels: ["PR type: bugfix 🕵️"]
    - title: "Miscellaneous"
      labels: ["PR type: miscellaneous 👾"]
    - title: "Documentation"
      labels: ["PR type: documentation 📚"]
    - title: "Dependencies"
      labels: ["PR type: dependencies 🤖"]
    - title: "Uncategorized"
      labels: ["*"]
