repos:
  - repo: builtin
    hooks:
      # File names
      - id: check-case-conflict
      # File formats
      - id: pretty-format-json
      - id: check-json
      - id: check-toml
      - id: check-yaml
      # Executables
      - id: check-executables-have-shebangs
        exclude: dev-env
      - id: check-shebang-scripts-are-executable
      # Git shenanigans
      - id: check-merge-conflict
      - id: check-added-large-files
      # Whitespace
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending

  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: uv run --group dev ruff check --force-exclude --fix --unsafe-fixes --show-fixes
        language: system
        types_or: [python, pyi]
        require_serial: true

      - id: ruff-format
        name: ruff format
        entry: uv run --group dev ruff format --force-exclude
        language: system
        types_or: [python, pyi, markdown]
        require_serial: true

      - id: uv-lock
        name: uv-lock
        entry: env UV_FROZEN=false uv lock
        language: system
        files: ^(uv\.lock|pyproject\.toml|uv\.toml)$
        pass_filenames: false

      - id: basedpyright
        name: basedpyright
        entry: uv run --all-groups basedpyright
        language: system
        types_or: [python, pyi]
        require_serial: true

      - id: doc8
        name: doc8
        entry: uv run --group dev doc8
        language: system
        types: [rst]
        require_serial: true

      - id: django-upgrade
        name: django-upgrade
        entry: uv run --group lint_format django-upgrade --target-version 4.2
        language: system
        types: [python]
        require_serial: true

      - id: zizmor
        name: zizmor
        entry: uv run --group dev zizmor --no-progress --fix=all
        language: system
        types: [yaml]
        files: (\.github/(workflows/.*|dependabot\.ya?ml))|(action\.ya?ml)$
        require_serial: true
