# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "latest"
  jobs:
    post_create_environment:
      - python -m pip install uv
    post_install:
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH python -m uv sync --group docs

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true
