# Generated by Django 3.1 on 2020-08-22 16:57

from django.db import migrations

import procrastinate.contrib.django


class Migration(migrations.Migration):

    initial = True

    dependencies: list = []

    operations = [
        procrastinate.contrib.django.RunProcrastinateFile(
            filename="baseline-0.5.0.sql",
        ),
    ]
