# Generated by Django 3.1 on 2020-08-22 16:57

from django.db import migrations

import procrastinate.contrib.django


class Migration(migrations.Migration):

    dependencies = [
        ("procrastinate", "0004_drop_procrastinate_version_table"),
    ]

    operations = [
        procrastinate.contrib.django.RunProcrastinateFile(
            filename="delta_0.6.0_001_fix_procrastinate_fetch_job.sql",
        ),
    ]
