# Generated by Django 3.1 on 2020-08-22 17:34

from django.db import migrations

import procrastinate.contrib.django


class Migration(migrations.Migration):

    dependencies = [
        ("procrastinate", "0010_add_procrastinate_periodic_defers"),
    ]

    operations = [
        procrastinate.contrib.django.RunProcrastinateFile(
            filename="delta_0.12.0_001_add_foreign_key_index.sql",
        ),
    ]
