# Generated by Django 3.1.1 on 2020-09-11 08:27

from django.db import migrations

import procrastinate.contrib.django


class Migration(migrations.Migration):

    dependencies = [
        ("procrastinate", "0011_add_foreign_key_index"),
    ]

    operations = [
        procrastinate.contrib.django.RunProcrastinateFile(
            filename="delta_0.14.0_001_add_locks_to_periodic_defer.sql",
        ),
    ]
