# Generated by Django 3.1.2 on 2020-10-05 10:50

from django.db import migrations

import procrastinate.contrib.django


class Migration(migrations.Migration):

    dependencies = [
        ("procrastinate", "0012_add_locks_to_periodic_defer"),
    ]

    operations = [
        procrastinate.contrib.django.RunProcrastinateFile(
            filename="delta_0.15.2_001_fix_procrastinate_defer_periodic_job.sql",
        ),
    ]
