# Generated by Django 5.1.6 on 2025-02-12 18:07
from __future__ import annotations

from django.db import migrations

from .. import migrations_utils


class Migration(migrations.Migration):
    dependencies = [
        ("procrastinate", "0035_post_add_heartbeat"),
    ]

    operations = [
        migrations_utils.RunProcrastinateSQL(
            name="03.02.00_01_add_retry_failed_job_procedure.sql"
        ),
    ]
