BEGIN;
SELECT plan(17);
SELECT has_type('procrastinate_job_status'::name);
SELECT has_type('procrastinate_job_event_type'::name);
SELECT has_table('procrastinate_jobs'::name);
SELECT has_table('procrastinate_events'::name);
SELECT has_table('procrastinate_job_locks'::name);
SELECT has_function('procrastinate_fetch_job'::name);
SELECT has_function('procrastinate_finish_job'::name);
SELECT has_function('procrastinate_notify_queue'::name);
SELECT has_function('procrastinate_trigger_status_events_procedure_insert'::name);
SELECT has_function('procrastinate_trigger_status_events_procedure_update'::name);
SELECT has_function('procrastinate_trigger_scheduled_events_procedure'::name);
SELECT has_index('procrastinate_jobs'::name, 'procrastinate_jobs_queue_name_idx'::name);
SELECT has_trigger('procrastinate_jobs'::name, 'procrastinate_jobs_notify_queue'::name);
SELECT has_trigger('procrastinate_jobs'::name, 'procrastinate_trigger_status_events_update'::name);
SELECT has_trigger('procrastinate_jobs'::name, 'procrastinate_trigger_status_events_insert'::name);
SELECT has_trigger('procrastinate_jobs'::name, 'procrastinate_trigger_scheduled_events'::name);
SELECT has_index('procrastinate_events'::name, 'procrastinate_events_job_id_fkey'::name);
SELECT finish();
ROLLBACK;
