#!/usr/bin/env bash
set -eu

# This script will take care of installing pipx for you (mainly on debian-based
# installations). It should not be run in a virtual environment. pipx, poetry
# and pre-commit are all tools that manage their own virtual environements, and
# are useful as tools to have around, and unlikely to cause version clashes
# between projects.


if ! which pre-commit || ! which poetry; then
    if ! which pipx; then
        python3 -m pip install --user pipx
        python3 -m pipx ensurepath
    fi
    if ! which pre-commit; then
        pipx install pre-commit
    fi
    if ! which poetry; then
        pipx install poetry
    fi
fi

pre-commit install
poetry install --extras "django sqlalchemy"
