#!/usr/bin/env bash
set -eux

poetry run sphinx-build -EW -b spelling docs docs/_build/html "$@"
# wordlist should be sorted to avoid duplicates
# If this line breaks, fix with:
# sort -bdfi docs/spelling_wordlist.txt -o docs/spelling_wordlist.txt
sort -cbdfi docs/spelling_wordlist.txt
