#!/bin/bash

set -euo pipefail

POETRY="poetry"
if [ -n "${CI:-}" ]; then
    set -x
    POETRY="pipx run poetry"
fi

# Poetry displays "(!)" before the dependencies that are not installed
export DEPS=$(
    ${POETRY} show\
    --only=main --only=types --top-level\
    --no-ansi --no-interaction\
    | sed 's/psycopg /psycopg[pool]/' \
    | awk '{printf "%s%s==%s",sep,$1,($2=="(!)" ? $3 : $2); sep="|"}'
)
# This should be something like:
#   aiopg==1.4.0|anyio==4.2.0|asgiref==3.7.2|...
yq -i \
    '(
        .repos[]
        | select( .repo | contains("pyright-python" ))
        | .hooks[].additional_dependencies
    ) = [
        strenv(DEPS) / "|"
        | .[]
        | select(length > 0)
    ]' \
    .pre-commit-config.yaml
