#!/usr/bin/env bash
set -eux

# This script is expected to be passed a PYPI_TOKEN env var

poetry version $(poetry run dunamai from git --pattern '(?P<base>\d+\.\d+\.\d+)')
poetry publish --no-interaction --build --username "__token__" --password "$PYPI_TOKEN"
git restore pyproject.toml
