name: autofix.ci
on: [pull_request]

env:
  UV_FROZEN: "true"

permissions:
  contents: read

jobs:
  lint:
    name: Autofix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up UV
        id: setup-uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          enable-cache: false
          python-version: "3.14"

      - name: Install dependencies
        run: uv sync --all-groups

      - name: Run prek
        uses: j178/prek-action@4e14d07f9231acabce116ccfca13b13dd9755ece # v3.0.0

      - name: Commits back to branch if necessary
        uses: autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a # v1.3.4
        if: failure()
